apiVersion: v1
kind: Pod
metadata:
  name: pod-command
  namespace: default
  labels:
    name: pod-command
spec:
  containers:
    - name: pod-command-nginx
      image: nginx
    - name: pod-command-buybox
      image: busybox
      command: ["/bin/sh","-c","touch /tmp/hello.txt;while true;do /bin/echo $(date +%T) >> /tmp/hello.txt; sleep 3; done;"]

